apiVersion: v1

hypershift:
  osImageVersion: "4.12"
  clusterImageSet: quay.io/openshift-release-dev/ocp-release:4.12.0-x86_64
  
metallb:
  apiAddressPool: "<cluster-name>-api-address-pool"

baseDomain: example.com
compute:
  - name: worker
    replicas: 2
metadata:
  name: r6-ocp-virt01
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  baremetal:
    apiVIP: 10.20.184.10
    ingressVIP: 10.20.184.11
    hosts:
      - name: r6-ocp-virt01-w03
        role: worker
        bmc:
          address: "redfish-virtualmedia://10.20.47.100/redfish/v1/Systems/1"
          credentialsName: "bmc-credentials"
        bootMACAddress: d4:f5:ef:7f:b1:1c
        rootDeviceHints:
          hctl: "1:0:0:0"
        networkConfig:
          dns-resolver:
            config:
              server:
                - 10.20.47.157
                - 10.21.47.157
          interfaces:
            - name: bond0
              type: bond
              state: up
              mac-address: d4:f5:ef:7f:b1:1c
              ipv4:
                enabled: true
                dhcp: false
                address:
                  - ip: 10.20.184.13
                    prefix-length: 24
              ipv6:
                enabled: false
              link-aggregation:
                mode: 802.3ad
                port:
                  - eno1np0
                  - eno2np1
            - name: eno1np0
              type: ethernet
              state: up
              mac-address: d4:f5:ef:7f:b1:1c
            - name: eno2np1
              type: ethernet
              state: up
              mac-address: d4:f5:ef:7f:b5:34
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 10.20.184.1
                next-hop-interface: bond0
                table-id: 254
pullSecret: "<pull secret>"
sshKey: |
  ssh-rsa ...