# Default values for deploy-cluster chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Base domain for the cluster
baseDomain: test.com

# Cluster metadata
metadata:
  name: test-cluster

# Compute nodes configuration
compute:
  - name: worker
    replicas: 2

# Networking configuration
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16

# Platform configuration for bare metal
platform:
  baremetal:
    apiVIP: 192.168.2.2
    ingressVIP: 192.168.3.3
    hosts:
      - name: openshift-worker-0
        role: worker
        bmc:
          address: "redfish-virtualmedia://10.100.100.100/redfish/v1/Systems/1"
          username: admin
          password: admin
        bootMACAddress: aa:aa:aa:aa:aa:aa
        rootDeviceHints:
          hctl: "1:0:0:0"
        networkConfig:
          interfaces:
            - name: eno1
              type: ethernet
              mac-address: aa:aa:aa:aa:aa:aa
              state: up
              ipv4:
                enabled: true
                dhcp: true
              ipv6:
                enabled: false
      - name: openshift-worker-1
        role: worker
        bmc:
          address: "redfish-virtualmedia://10.100.100.200/redfish/v1/Systems/1"
          username: admin
          password: admin
        bootMACAddress: bb:bb:bb:bb:bb:bb
        rootDeviceHints:
          hctl: "2:0:0:0"
        networkConfig:
          interfaces:
            - name: eno1
              type: ethernet
              mac-address: bb:bb:bb:bb:bb:bb
              state: up
              ipv4:
                enabled: true
                dhcp: true
              ipv6:
                enabled: false

# External Secrets Configuration
externalSecrets:
  # Pull secret for container registry authentication
  - name: "assisted-deployment-pull-secret"
    type: "pull-secret"
    # Use existing secret instead of ExternalSecret
    # ref: "my-existing-pull-secret"
    secretStore:
      name: "pull-secret-store"
      kind: "SecretStore"
    remoteKey: "pull-secret"
    remoteProperty: "dockerconfigjson"
  
  # BMC credentials for bare metal hosts
  - name: "bmc-credentials"
    type: "bmc-secret"
    secretStore:
      name: "bmc-secret-store"
      kind: "SecretStore"
    remoteKey: "bmc-credentials"
    data:
      - secretKey: "username"
        remoteProperty: "username"
      - secretKey: "password"
        remoteProperty: "password"

# SSH key for cluster access
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7vbqajDhA... example@example.com

# HyperShift specific configuration
hypershift:
  osImageVersion: "4.12"
  clusterImageSet: quay.io/openshift-release-dev/ocp-release:4.12.0-x86_64

# MetalLB Configuration
metallb:
  apiAddressPool: "test-cluster-api-address-pool"

# Additional configuration (optional)
# additionalTrustBundle: |
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----

# imageContentSources:
#   - mirrors:
#     - quay-mirror.example/openshift-release-dev/ocp-release
#     source: quay.io/openshift-release-dev/ocp-release
