{{- $namespace := .Values.metadata.name }}
{{- range .Values.platform.baremetal.hosts }}
{{- if not (hasKey .bmc "credentialsName") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .name }}-bmc-secret"
  namespace: {{ $namespace | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bmc-secret-store
    kind: SecretStore
  target:
    name: "{{ .name }}-bmc-secret"
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: bmc-credentials
      property: "{{ .name }}-username"
  - secretKey: password
    remoteRef:
      key: bmc-credentials
      property: "{{ .name }}-password"
---
{{- end }}
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: {{ .name | quote }}
  namespace: {{ $namespace | quote }}
  annotations:
    bmac.agent-install.openshift.io/role: "worker"
    bmac.agent-install.openshift.io/hostname: {{ .name | quote }}
    helm.sh/hook-weight: "15"
  labels:
    infraenvs.agent-install.openshift.io: {{ .role | quote }}
spec:
  bootMode: {{ .bootMode | default "UEFI" | quote }}
  bmc:
    address: {{ .bmc.address | quote }}
    disableCertificateVerification: true
    credentialsName: {{ if hasKey .bmc "credentialsName" }}{{ .bmc.credentialsName | quote }}{{ else }}"{{ .name }}-bmc-secret"{{ end }}
  bootMACAddress: {{ .bootMACAddress | quote }}
  online: true
  {{- if hasKey . "rootDeviceHints" }}
  rootDeviceHints:
    {{- .rootDeviceHints | toYaml | nindent 4 }}
  {{- end }}
  {{- if hasKey . "raid" }}
  raid:
    {{- .raid | toYaml | nindent 4 }}
  {{- end }}
  {{- if hasKey . "firmware" }}
  firmware:
    {{- .firmware | toYaml | nindent 4 }}
  {{- end }}
---
{{- end }}
