{{- $namespace := .Values.metadata.name }}
{{- $bmcSecret := dict }}
{{- range .Values.externalSecrets }}
{{- if eq .type "bmc-secret" }}
{{- $bmcSecret = . }}
{{- end }}
{{- end }}
{{- if not $bmcSecret }}
{{- $bmcSecret = dict "secretStore" (dict "name" "bmc-secret-store" "kind" "SecretStore") "remoteKey" "bmc-credentials" "data" (list (dict "secretKey" "username" "remoteProperty" "username") (dict "secretKey" "password" "remoteProperty" "password")) }}
{{- end }}
{{- range .Values.platform.baremetal.hosts }}
{{- $hostName := .name }}
{{- if not (hasKey .bmc "credentialsName") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .name }}-bmc-secret"
  namespace: {{ $namespace | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $bmcSecret.secretStore.name }}
    kind: {{ $bmcSecret.secretStore.kind }}
  target:
    name: "{{ .name }}-bmc-secret"
    creationPolicy: Owner
  data:
{{- range $bmcSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ $bmcSecret.remoteKey }}
      property: "{{ $hostName }}-{{ .remoteProperty }}"
{{- end }}
---
{{- end }}
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: {{ .name | quote }}
  namespace: {{ $namespace | quote }}
  annotations:
    bmac.agent-install.openshift.io/role: "worker"
    bmac.agent-install.openshift.io/hostname: {{ .name | quote }}
    helm.sh/hook-weight: "15"
  labels:
    infraenvs.agent-install.openshift.io: {{ .role | quote }}
spec:
  bootMode: {{ .bootMode | default "UEFI" | quote }}
  bmc:
    address: {{ .bmc.address | quote }}
    disableCertificateVerification: true
    credentialsName: {{ if hasKey .bmc "credentialsName" }}{{ .bmc.credentialsName | quote }}{{ else }}"{{ .name }}-bmc-secret"{{ end }}
  bootMACAddress: {{ .bootMACAddress | quote }}
  online: true
  {{- if hasKey . "rootDeviceHints" }}
  rootDeviceHints:
    {{- .rootDeviceHints | toYaml | nindent 4 }}
  {{- end }}
  {{- if hasKey . "raid" }}
  raid:
    {{- .raid | toYaml | nindent 4 }}
  {{- end }}
  {{- if hasKey . "firmware" }}
  firmware:
    {{- .firmware | toYaml | nindent 4 }}
  {{- end }}
---
{{- end }}
