{{- $namespace := .Values.metadata.name }}
{{- $osversion := .Values.hypershift.osImageVersion }}
{{- $sshkey := .Values.sshKey }}
{{- $ntpsources := .Values.hypershift.additionalNTPSources | default list }}
{{- $proxy := .Values.proxy | default dict }}
{{- $nodepoolconfigs := .Values.hypershift.nodePoolConfigs }}
{{- range .Values.compute }}
{{- $poolconfig:= dict }}
{{- $poolname := .name }}
  {{- range $nodepoolconfigs }}
    {{- if eq .name $poolname }}
      {{- $poolconfig = . }}
    {{- end }}
  {{- end }}
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: {{ .name | quote }}
  namespace: {{ $namespace | quote }}
  annotations:
    helm.sh/hook-weight: "10"
spec:
  osImageVersion: "{{ $poolconfig.osImageVersion | default $osversion }}"
  sshAuthorizedKey: "{{ $sshkey | trim }}"
  pullSecretRef:
    name: assisted-deployment-pull-secret
  nmStateConfigLabelSelector:
    matchLabels:
      nmstate-cluster: {{ .name | quote }}
{{- if ne (len $ntpsources) 0 }}
  additionalNTPSources:
    {{- $ntpsources | toYaml | nindent 4 }}
{{- end }}
{{- if ne (len $proxy) 0 }}
  proxy:
    {{- $proxy | toYaml | nindent 4 }}
{{- end }}
---
{{- end }}
