{{- if not (hasKey .Values "pullSecretRef") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: assisted-deployment-pull-secret
  namespace: {{ .Values.metadata.name | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pull-secret-store
    kind: SecretStore
  target:
    name: assisted-deployment-pull-secret
    creationPolicy: Owner
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: pull-secret
      property: dockerconfigjson
{{- end }}
