apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hypershift-installer-role
  namespace: "{{ .Values.metadata.name }}-{{ .Values.metadata.name }}"
  annotations:
    helm.sh/hook-weight: "30"
rules:
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hypershift-installer-binding
  namespace: "{{ .Values.metadata.name }}-{{ .Values.metadata.name }}"
  annotations:
    helm.sh/hook-weight: "30"
subjects:
  - kind: ServiceAccount
    name: hypershift-installer
    namespace: {{ .Values.metadata.name | quote }}
roleRef:
  kind: Role
  name: hypershift-installer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hypershift-installer
  namespace: {{ .Values.metadata.name | quote }}
