name: Build project

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Charts
        run: |
          helm lint chart/
          
      - name: Package Charts
        run: |
          helm package chart/
          
      - name: Run Tests
        run: |
          ./tests/run_tests.sh
          
      - name: Test Chart Installation
        run: |
          helm install test-cluster ./chart --values tests/configs/minimal.yaml --dry-run
